apiVersion: v2
name: emr-monitoring
version: 1.0.0
appVersion: 1.0.0
description: Enterprise-grade monitoring stack for EMR Task Management platform featuring Prometheus, Grafana, and AlertManager with healthcare-specific monitoring capabilities, HIPAA compliance features, and high-availability configuration
type: application

keywords:
  - monitoring
  - prometheus
  - grafana
  - alertmanager
  - healthcare
  - emr
  - hipaa-compliant
  - high-availability

maintainers:
  - name: EMR Task Platform Team
    email: platform@emrtask.com
    url: https://emrtask.com/platform

annotations:
  healthcare.compliance: hipaa
  availability.target: "99.99"
  monitoring.scope: full-stack

dependencies:
  - name: prometheus
    version: 2.44.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    tags:
      - metrics
      - monitoring
      - healthcare

  - name: grafana
    version: 9.5.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
    tags:
      - visualization
      - dashboards
      - healthcare

  - name: alertmanager
    version: 0.25.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: alertmanager.enabled
    tags:
      - alerts
      - notifications
      - healthcare