apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-service
  namespace: default
  labels:
    app: sync-service
    component: backend
    tier: sync
  annotations:
    kubernetes.io/change-cause: "Initial deployment with HA configuration"
spec:
  # Triple redundancy for 99.99% uptime requirement
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Zero-downtime deployment configuration
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sync-service
  template:
    metadata:
      labels:
        app: sync-service
        component: backend
        tier: sync
      annotations:
        # Prometheus metrics configuration for performance monitoring
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      # Pod anti-affinity for high availability across nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: sync-service
      containers:
      - name: sync-service
        image: sync-service:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        # Resource allocation optimized for CRDT operations
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        # Health monitoring configuration
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
      # Security context for non-root execution
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      # Grace period for clean shutdown
      terminationGracePeriodSeconds: 60