# Helm chart values for EMR Task Management platform's logging stack
# Version: 7.17.3
# Components: Elasticsearch, Kibana, Filebeat

global:
  environment: production
  storageClass: gp2
  imageRegistry: docker.elastic.co

elasticsearch:
  enabled: true
  replicas: 3
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 7.17.3
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  
  persistence:
    enabled: true
    storageClass: gp2
    size: 100Gi
    accessModes:
      - ReadWriteOnce
  
  security:
    enabled: true
    tls:
      enabled: true
      verificationMode: certificate
    authentication:
      enabled: true
      existingSecret: elasticsearch-credentials
  
  monitoring:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s

kibana:
  enabled: true
  replicas: 2
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 7.17.3
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
  
  security:
    enabled: true
    tls:
      enabled: true

filebeat:
  enabled: true
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.17.3
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 400Mi
  
  config:
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path
    
    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOSTS}"]
      protocol: https
      ssl.verification_mode: certificate
  
  monitoring:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s