apiVersion: v1
kind: Service

metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    # Prometheus metrics collection configuration
    prometheus.io/scrape: "{{ .Values.kong.metrics.enabled }}"
    prometheus.io/port: "{{ .Values.kong.metrics.port }}"
    prometheus.io/path: "{{ .Values.kong.metrics.annotations.prometheus_io_path }}"
    # AWS Load Balancer specific configurations for high availability
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    # Additional security headers
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "{{ .Values.kong.proxy.tls.port }}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"

spec:
  type: {{ .Values.kong.proxy.type }}
  # Port configuration for proxy, SSL, admin, and metrics
  ports:
    # HTTP proxy port
    - name: proxy
      port: {{ .Values.kong.proxy.http.port }}
      targetPort: {{ .Values.kong.proxy.http.port }}
      protocol: TCP
    
    # HTTPS/TLS proxy port
    - name: proxy-ssl
      port: {{ .Values.kong.proxy.tls.port }}
      targetPort: {{ .Values.kong.proxy.tls.port }}
      protocol: TCP
    
    # Admin TLS port (if enabled)
    {{- if .Values.kong.admin.enabled }}
    - name: admin-ssl
      port: {{ .Values.kong.admin.tls.port }}
      targetPort: {{ .Values.kong.admin.tls.port }}
      protocol: TCP
    {{- end }}
    
    # Metrics port for Prometheus
    {{- if .Values.kong.metrics.enabled }}
    - name: metrics
      port: {{ .Values.kong.metrics.port }}
      targetPort: {{ .Values.kong.metrics.port }}
      protocol: TCP
    {{- end }}
  
  # Selector to match pods from the deployment
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}

  # Session affinity for consistent routing
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

  # External traffic policy for better security
  externalTrafficPolicy: Local

  # Health check configuration
  healthCheckNodePort: {{ add 30000 (int .Values.kong.proxy.http.port) }}