platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

target 'EMRTask' do
  pod 'Firebase/Analytics', '~> 10.0'
  pod 'Firebase/Crashlytics', '~> 10.0'
  pod 'KeychainAccess', '~> 4.2'
  pod 'CryptoSwift', '~> 1.8'
  pod 'Alamofire', '~> 5.8'
  pod 'RealmSwift', '~> 10.42'
  pod 'MLKitBarcodeScanning', '~> 3.0'
  pod 'SwiftProtobuf', '~> 1.25'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PERMISSION_CAMERA=1']
      config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)', '-ObjC']
      config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
    end
  end
end