{{/* 
Istio DestinationRule template for EMR Task Management platform
Version: 1.18+
Purpose: Defines traffic management policies, load balancing, and mTLS settings
*/}}

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  {{- template "istio.metadata" . }}
  labels:
    app.kubernetes.io/component: traffic-management
    security.istio.io/tlsMode: istio
    monitoring.istio.io/enabled: "true"
spec:
  {{- if .Values.global.host }}
  host: {{ .Values.global.host }}
  {{- else }}
  host: {{ include "istio.serviceName" . }}
  {{- end }}
  trafficPolicy:
    # Load balancing configuration for optimal request distribution
    loadBalancer:
      simple: ROUND_ROBIN
    
    # Connection pool settings for TCP and HTTP traffic
    connectionPool:
      tcp:
        maxConnections: {{ .Values.destinationRules.connectionPool.tcp.maxConnections | default 100 }}
        connectTimeout: {{ .Values.destinationRules.connectionPool.tcp.connectTimeout | default "5s" }}
      http:
        http1MaxPendingRequests: {{ .Values.destinationRules.connectionPool.http.maxPendingRequests | default 100 }}
        maxRequestsPerConnection: {{ .Values.destinationRules.connectionPool.http.maxRequestsPerConnection | default 100 }}
        maxRetries: {{ .Values.destinationRules.connectionPool.http.maxRetries | default 3 }}
    
    # Circuit breaking and outlier detection for fault tolerance
    outlierDetection:
      consecutive5xxErrors: {{ .Values.destinationRules.outlierDetection.consecutive5xxErrors | default 5 }}
      interval: {{ .Values.destinationRules.outlierDetection.interval | default "30s" }}
      baseEjectionTime: {{ .Values.destinationRules.outlierDetection.baseEjectionTime | default "30s" }}
      maxEjectionPercent: {{ .Values.destinationRules.outlierDetection.maxEjectionPercent | default 100 }}
    
    # Mutual TLS settings for secure service-to-service communication
    tls:
      mode: ISTIO_MUTUAL
      {{- if .Values.destinationRules.tls.customSettings }}
      {{- toYaml .Values.destinationRules.tls.customSettings | nindent 6 }}
      {{- end }}

  {{- if .Values.destinationRules.subsets }}
  # Service subsets for granular traffic management
  subsets:
    {{- toYaml .Values.destinationRules.subsets | nindent 4 }}
  {{- end }}

  {{- if .Values.destinationRules.customTrafficPolicy }}
  # Additional custom traffic policy settings
  {{- toYaml .Values.destinationRules.customTrafficPolicy | nindent 2 }}
  {{- end }}