# Elasticsearch Service Template
# Version: 7.17.3
# Purpose: Defines a headless Kubernetes service for Elasticsearch cluster communication and client access
# Supports: High availability, metrics collection, and StatefulSet integration

apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: elk-stack
    app.kubernetes.io/managed-by: helm
    {{- if .Values.elasticsearch.service.labels }}
    {{- toYaml .Values.elasticsearch.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    # Enable Prometheus metrics scraping
    prometheus.io/scrape: "true"
    prometheus.io/port: "9114"
    # Allow endpoints to be considered ready before they can accept traffic
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- if .Values.elasticsearch.service.annotations }}
    {{- toYaml .Values.elasticsearch.service.annotations | nindent 4 }}
    {{- end }}

spec:
  # Headless service for StatefulSet pod discovery
  type: ClusterIP
  clusterIP: None
  # Required for proper StatefulSet DNS resolution during cluster formation
  publishNotReadyAddresses: true
  
  ports:
    # REST API and HTTP interface
    - name: http
      port: 9200
      targetPort: http
      protocol: TCP
    
    # Inter-node communication port
    - name: transport
      port: 9300
      targetPort: transport
      protocol: TCP
      
    # Prometheus metrics exporter port
    - name: metrics
      port: 9114
      targetPort: metrics
      protocol: TCP
      
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.elasticsearch.service.selector }}
    {{- toYaml .Values.elasticsearch.service.selector | nindent 4 }}
    {{- end }}