apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kibana.fullname" . }}
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: elk-stack
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5601"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kibana
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5601"
        checksum/config: {{ include (print $.Template.BasePath "/kibana-config.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup | default 1000 }}
        runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
        runAsNonRoot: true
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://{{ template "elasticsearch.fullname" . }}:9200
            - name: SERVER_PORT
              value: "5601"
            - name: ELASTICSEARCH_URL
              value: http://{{ template "elasticsearch.fullname" . }}:9200
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1800"
            - name: LOGGING_VERBOSE
              value: "true"
            - name: TELEMETRY_ENABLED
              value: "false"
            {{- if .Values.kibana.extraEnvs }}
            {{- toYaml .Values.kibana.extraEnvs | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
            {{- if .Values.kibana.extraVolumeMounts }}
            {{- toYaml .Values.kibana.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: kibana-config
          configMap:
            name: {{ template "kibana.fullname" . }}-config
        {{- if .Values.kibana.extraVolumes }}
        {{- toYaml .Values.kibana.extraVolumes | nindent 8 }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}