apiVersion: v1
kind: Service
metadata:
  name: handover-service
  namespace: default
  labels:
    app: handover-service
    component: backend
    part-of: emr-task-platform
    version: v1
  annotations:
    # Prometheus monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "3003"
    prometheus.io/path: "/metrics"
    # Istio service mesh integration
    sidecar.istio.io/inject: "true"
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: handover-service
  sessionAffinity: None