apiVersion: v2
type: application
name: api-gateway
description: API Gateway powered by Kong for EMR Task Management Platform with HIPAA-compliant routing and security features
version: 1.0.0
appVersion: "3.4.0"
kubeVersion: ">=1.26.0"

maintainers:
  - name: EMR Task Platform Team
    email: platform@emrtask.com

dependencies:
  - name: kong
    version: 3.4.0
    repository: https://charts.konghq.com
    condition: kong.enabled
    tags:
      - gateway
      - proxy
      - healthcare
  - name: metrics-server
    version: 3.8.0
    repository: https://kubernetes-sigs.github.io/metrics-server/
    condition: metrics-server.enabled
    tags:
      - monitoring
      - scaling

keywords:
  - api-gateway
  - kong
  - healthcare
  - emr
  - proxy
  - hipaa-compliant
  - fhir
  - hl7
  - high-availability

home: https://emrtask.com
sources:
  - https://github.com/emrtask/emr-task-platform

annotations:
  artifacthub.io/changes: "Initial release of API Gateway chart with HIPAA compliance and high availability features"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/recommendations: "true"
  artifacthub.io/signKey: "fingerprint: 0123456789abcdef"
  healthcare.config/hipaa-ready: "true"
  monitoring.config/prometheus-enabled: "true"
  security.config/tls-enabled: "true"
  availability.config/multi-az: "true"