apiVersion: v2
name: argocd
description: ArgoCD deployment for EMR-Integrated Task Management Platform
version: 1.0.0
appVersion: "2.8.0"
type: application

keywords:
  - gitops
  - continuous-deployment
  - kubernetes

maintainers:
  - name: EMR Task Platform Team
    email: devops@emrtask.com

# Dependencies required for ArgoCD deployment
dependencies:
  # Redis for caching and session management
  - name: redis
    version: 17.8.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  # Prometheus for monitoring and metrics
  - name: prometheus
    version: 15.18.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

annotations:
  category: CI/CD
  licenses: Apache-2.0
  support: EMR Task Platform Team

# Additional metadata for EMR platform requirements
kubeVersion: ">=1.22.0"
home: https://emrtask.com/argocd
sources:
  - https://github.com/emrtask/argocd-deployment
icon: https://emrtask.com/icons/argocd.png