apiVersion: v2
name: vault
description: HashiCorp Vault deployment for EMR-Integrated Task Management Platform
version: 1.0.0
appVersion: "1.13.0"
type: application
keywords:
  - secrets
  - security
  - encryption
  - key-management
  - healthcare

maintainers:
  - name: EMR Task Platform Team
    email: devops@emrtask.internal

dependencies:
  - name: vault
    version: 1.13.0
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
    tags:
      - secrets
      - security
      - healthcare

kubeVersion: ">=1.26.0"
home: https://github.com/emrtask/emr-task-platform
sources:
  - https://github.com/emrtask/emr-task-platform
  - https://www.vaultproject.io/

annotations:
  artifacthub.io/changes: "Initial release of Vault chart for EMR Task Platform"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/prerelease: "false"
  healthcare.security/hipaa-compliant: "true"
  healthcare.security/key-rotation: "365-days"
  healthcare.security/hsm-enabled: "true"